//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leerlingvolgsysteem.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountAuthorication> AccountAuthorication { get; set; }
        public virtual DbSet<AccountClass> AccountClass { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<ClassCourse> ClassCourse { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<SchoolAccount> SchoolAccount { get; set; }
        public virtual DbSet<SchoolClass> SchoolClass { get; set; }
        public virtual DbSet<SchoolCourse> SchoolCourse { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
