//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leerlingvolgsysteem.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string zipCode { get; set; }
        public string place { get; set; }
        public string Department { get; set; }
    }
}
